routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Product;
use Symfony\Component\Console\Input\Input;

Route::pattern('id_slider', '[0-9]+');
Route::pattern('id_category', '[0-9]+');
Route::pattern('id_brand', '[0-9]+');
Route::pattern('id_basket', '[0-9]+');
Route::pattern('id_product', '[0-9]+');
Route::pattern('id_promocode', '[0-9]+');

//URL::forceScheme('https');
Route::post('/ajax_login', 'Auth\LoginController@ajaxLogin')->name("ajax_login");
Auth::routes();


Route::get('/', 'MainPageController@main')->name("home");
Route::get('/yml', 'YmlController@index')->name("sitemap");
Route::get('/content/{slug}', 'SiteRedirectController@redirect');

Route::group(['prefix' => 'blocks', 'as' => 'blocks.'], function () {
    Route::get("/popular_products", "MainPageController@popularProducts")->name("popular_products");
    Route::get("/products_category/{id}", "MainPageController@productsCategory")->name("products_category");
});

/* Static Pages routing */
Route::prefix('page')->group(function () {
    Route::get('/contact', 'StaticPagesController@contact')->name('contact');
    Route::get('/shipping', 'StaticPagesController@shipping')->name('shipping');
    Route::get('/gifts', 'StaticPagesController@gifts')->name('gifts');
    Route::get('/price_list', 'StaticPagesController@priceList')->name('price_list');
    Route::get('/cooperation', 'StaticPagesController@cooperation')->name('cooperation');
    Route::get('/job_offers', 'StaticPagesController@jobOffers')->name('job_offers');
    Route::get('/purchase_rules', 'StaticPagesController@purchaseRules')->name('purchase_rules');
});

Route::group([], function () {
    Route::get('/search', 'SearchController@index')->name('search');

    Route::group(['as' => 'payments.', 'prefix' => 'payments'], function () {
        Route::get('/success', 'PaymentsController@success')->name('success');
        Route::get('/error', 'PaymentsController@error')->name('error');
    });

    Route::group(['as' => 'orders.', 'prefix' => 'order'], function () {
        Route::post('/', 'OrdersController@store')->name('store');
        Route::post('/one_click', 'OrdersController@byOneClick')->name('by_one_click');
    });

    Route::group(['as' => 'user.', 'prefix' => 'user'], function () {
        Route::get('/edit', 'UsersController@edit')->name('user.edit');
    });

    Route::group(['as' => 'news.', 'prefix' => 'news'], function () {
        Route::get('/', 'ArticlesController@index')->name('index');
        Route::get('/{id}', 'ArticlesController@show')->name('show');
    });

    Route::group(['as' => 'categories.', 'prefix' => 'categories'], function () {
        Route::get('/', 'CategoriesController@index')->name('index');
        Route::get('/products', 'CategoriesController@getProducts')->name("products");
        Route::get('/filters/{slug}', 'CategoriesController@filters')->name("filters");
        Route::get('/{slug}', 'CategoriesController@show')->name("page");
    });

    Route::group(['as' => 'products.', 'prefix' => 'products'], function () {
        Route::get('/{slug}/{size?}/{color?}', 'ProductsController@show')->name("page");
    });

    Route::group(['as' => 'likes.', 'prefix' => 'likes'], function () {
        Route::get('/', 'LikesController@index')->name("index");
        Route::post('/', 'LikesController@store')->name("store");
        Route::delete('/', 'LikesController@destroy')->name("destroy");
    });

    Route::group(['as' => 'comments.', 'prefix' => 'comments'], function () {
        Route::get('/{product_id}', 'CommentsController@index')->name("index");
        Route::post('/{product_id}', 'CommentsController@store')->name("store");
    });

    Route::group(['as' => 'baskets.', 'prefix' => 'baskets'], function () {
        Route::get('/', 'BasketsController@index')->name('index');
        Route::get('/data', 'BasketsController@getData')->name('get_data');
        Route::put('/{product_id}', 'BasketsController@update')->name('update');
        Route::post('/', 'BasketsController@store')->name('store');
        Route::delete('/{product_id?}', 'BasketsController@destroy')->name('destroy');
    });
});

Route::group(['prefix' => 'admin1', 'as' => 'admin.'], function () {
    Route::get("statistics", "Admin\StatisticsController@getStatistics");
    Route::get("orders", "Admin\OrdersController@index");
    Route::get("brands", "Admin\BrandsController@index");
    Route::get("categories", "Admin\CategoriesController@index");
    Route::get("users", "Admin\UsersController@index");
});

/* Admin routing */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware'=>['auth', 'role:admin']], function () {
    Route::get('/', 'StaticPagesController@admin')->name("main");

    Route::group(['as' => 'charts.', 'prefix' => 'charts'], function () {
        Route::get('/orders_for_registered_or_not', 'Admin\ChartsController@ordersForRegisteredOrNot')->name('orders_for_registered_or_not');
        Route::get('/avg_orders_sum', 'Admin\ChartsController@avgOrdersSum')->name('avg_orders_sum');
        Route::get('/statistics_per_month', 'Admin\ChartsController@statisticsPerMonth')->name('statistics_per_month');
    });


    Route::resource('/products', 'Admin\ProductsController', [
        'names' => [
            'index' => 'products.index',
            'show' => 'products.show',
            'create' => 'products.create',
            'update' => 'products.update',
            'edit' => 'products.edit',
            'store' => 'products.store',
            'destroy' => 'products.destroy',
        ],
        'parameters' => [
            'products' => 'id_product'
        ]
    ]);

    Route::resource('/brands', 'Admin\BrandsController', [
        'names' => [
            'index' => 'brands.index',
            'create' => 'brands.create',
            'update' => 'brands.update',
            'edit' => 'brands.edit',
            'store' => 'brands.store',
            'destroy' => 'brands.destroy',
        ],
        'parameters' => [
            'brands' => 'id_brand'
        ]
    ])->except('show');

    Route::resource('/categories', 'Admin\CategoriesController', [
        'names' => [
            'index' => 'categories.index',
            'create' => 'categories.create',
            'update' => 'categories.update',
            'edit' => 'categories.edit',
            'store' => 'categories.store',
            'destroy' => 'categories.destroy',
        ],
        'parameters' => [
            'categories' => 'id_category'
        ]
    ])->except('show');

    Route::resource('/comments', 'Admin\CommentsController', [
        'name' => [
            'index' => 'comments.index',
            'update' => 'comments.update',
            'destroy' => 'comments.destroy',
        ],
        'parameters' => [
            'comments' => 'id_comment',
        ]
    ])->except(['show', 'create', 'edit', 'store']);

    Route::resource('/delivery_types', 'Admin\DeliveryTypesController', [
        'name' => [
            'index' => 'delivery_types.index',
            'create' => 'delivery_types.create',
            'update' => 'delivery_types.update',
            'edit' => 'delivery_types.edit',
            'store' => 'delivery_types.store',
            'destroy' => 'delivery_types.destroy',
        ],
        'parameters' => [
            'delivery_types' => 'id_delivery_type',]
    ])->except('show');


    Route::resource('/slider', 'Admin\SliderController', [
        'names' => [
            'create' => 'slider.create',
            'store' => 'slider.store',
            'update' => 'slider.update',
            'edit' => 'slider.edit',
            'destroy' => 'slider.destroy',
        ],
        'parameters' => [
            'slider' => 'id_slider'
        ]
    ])->except(['show']);

    Route::resource('/users', 'Admin\UsersController', [
        'names' => [
            'index' => 'users.index',
            'create' => 'users.create',
            'store' => 'users.store',
            'edit' => 'users.edit',
            'update' => 'users.update',
            'destroy' => 'users.destroy'
        ],
        'parameters' => [
            'users' => 'id_user'
        ]
    ])->except('show');
    Route::put('/users/{id_user}/edit', 'Admin\UsersController@updatePassword')->name('users.update_password');

    Route::resource('/articles', 'Admin\ArticlesController', [
        'names' => [
            'index' => 'articles.index',
            'create' => 'articles.create',
            'update' => 'articles.update',
            'edit' => 'articles.edit',
            'store' => 'articles.store',
            'destroy' => 'articles.destroy',
        ],
        'parameters' => [
            'articles' => 'id_article'
        ]
    ])->except('show');

    Route::resource('/promocodes', 'Admin\PromocodesController', [
        'name' => [
            'index' => 'promocodes.index',
            'create' => 'promocodes.create',
            'update' => 'promocodes.update',
            'edit' => 'promocodes.edit',
            'store' => 'promocodes.store',
            'destroy' => 'promocodes.destroy',
        ],
        'parameters' => [
            'promocodes' => 'id_promocode',
        ]
    ])->except('show');

    Route::resource('/orders', 'Admin\OrdersController', [
        'name' => [
            'index' => 'orders.index',
            'show' => 'orders.show',
            'create' => 'orders.create',
            'update' => 'orders.update',
            'edit' => 'orders.edit',
            'store' => 'orders.store',
            'destroy' => 'orders.destroy',
        ],
        'parameters' => [
            'orders' => 'id_order',
        ]

app/Http/Controllers/Admin/ArticlesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Category;
use App\Http\Controllers\SiteController;
use App\Product;
use App\ProductsArticle;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Illuminate\View\View;

/**
 * Class ArticlesController
 *
 * @package App\Http\Controllers\Admin
 */
class ArticlesController extends SiteController
{
    private $articlesInPage = 10;

    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $articles = Article::orderBy('created_at', 'desc')->paginate($this->articlesInPage);

        return $this->renderOutputAdmin("admin.articles.list", [
            "articles" => $articles
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        $categories = Category::orderBy("name")->with('products')->get();

        return $this->renderOutputAdmin("admin.articles.form", [
            'categories' => $categories,
            "route" => route("admin.articles.store")
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return JsonResponse|Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'content' => 'required',
            'category_id' => 'required',
            'images' => 'required|min:1'
        ]);

        if ($validator->fails()) {
            return response()->json(['mess' => $validator->errors()->all(), 'success' => false], 400);
        }

        $userUploadedImg = $this->loadImages(json_decode($request->images), null, 600);

        if (sizeof($userUploadedImg) > 1) {
            $data["success"] = false;
            $data["mess"] = "Допустимое количество изображений - не более одного";
            return response()->json($data, 400);
        }

        $articleId = Article::create([
            'name' => $request->name,
            'content' => $request->input('content'),
            'image' => $userUploadedImg[0],
            'image_caption' => $request->input('image_caption', null),
            'category_id' => $request->category_id,
            'is_promotion' => $request->is_promotion
        ])->id;

        if ($request->products) {
            $articleProducts = $request->products;

            foreach ($articleProducts as $articleProduct) {
                ProductsArticle::create([
                    "article_id" => $articleId,
                    "product_id" => $articleProduct
                ]);
            }
        }

        return redirect()->route("admin.articles.index")->withSuccess("Статья успешно добавлена");
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Factory|View
     */
    public function edit($id)
    {
        $article = Article::whereId($id)->with('productsArticles')->first();
        $categoriesInfo = Category::all();
        $chosenProducts = ProductsArticle::where('article_id', $id)->get()->pluck('product_id')->toArray();

        return $this->renderOutputAdmin("admin.articles.form", [
            "article" => $article,
            'categories' => $categoriesInfo,
            'chosen_products' => $chosenProducts,
            "route" => route("admin.articles.update", ["id_article" => $id]),
            "update" => true
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return JsonResponse|void
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'content' => 'required'
        ]);

        if ($validator->fails()) {
            $data["success"] = false;
            $data["mess"] = $validator->errors()->first();
            return response()->json($data, 400);
        }

        $images = json_decode($request->images);

        $userUploadedImg = $this->loadImages($images, 800, null);

        if (sizeof($userUploadedImg) > 1) {
            $data["success"] = false;
            $data["mess"] = "Допустимое количество изображений - не более одного";
            return response()->json($data, 400);
        }

        Article::whereId($id)->update(
            [
                'name' => $request->name,
                'content' => $request->input('content'),
                'image_caption' => $request->image_caption,
                'category_id' => $request->category_id,
                'is_promotion' => $request->is_promotion,
                'image' => $userUploadedImg[0]
            ]
        );

        ProductsArticle::where("article_id", $id)->delete();

        if ($request->products) {
            $articleProducts = $request->products;

            foreach ($articleProducts as $articleProduct) {
                ProductsArticle::create([
                    "article_id" => $id,
                    "product_id" => $articleProduct
                ]);
            }
        }

        return response()->json(['mess' => "Статья успешно изменена", 'success' => true], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     * @throws Exception
     */
    public function destroy($id)
    {
        Article::whereId($id)->delete();
        return redirect()->route("admin.articles.index")->withSuccess("Статья успешно удалена");
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

/**
 * Class ArticlesController
 *
 * @package App\Http\Controllers
 */
class ArticlesController extends SiteController
{
    /**
     * Get list articles.
     *
     * @return Factory|View
     */
    public function index()
    {
        $articles = Article::orderBy('created_at', 'desc')->get();

        return $this->renderOutput('articles.list', [
            'articles' => $articles,
        ]);
    }

    /**
     * Show articles.
     *
     * @param $articleId
     * @return Factory|RedirectResponse|View
     */
    public function show($articleId)
    {
        $article = Article::whereId($articleId)->first();
        if ($article == null) {
            return redirect()->route("home");
        }
        return $this->renderOutput('articles.page', [
            'article' => $article
        ]);
    }
}

resources/views/admin/articles/form.blade.php
@extends('layouts.admin_app')

@section('content')
    <div class="title-bar">
        <h1 class="title-bar-title">
            <span class="d-ib">
                @if($update ?? false)
                    Изменить статью
                @else
                    Добавить статью
                @endif
            </span>
        </h1>
    </div>

    <div class="row">
        <div class="col-md-8">
            <div class="demo-form-wrapper">
                @if (session('errors'))
                    <div class="alert alert-danger" role="alert">
                        {{ session('errors')->first() }}
                    </div>
                @endif

                <form class="form form-horizontal create_article" action="{{ $route }}" method="post">
                    <input type="hidden" id="update" value="{{ $update ?? false }}">
                    <input type="hidden" id="id_article" value="{{ $article->id ?? false }}">
                    <div class="form-group">

                        <div class="label-for-admin">
                        <p class="col-sm-3 control-label">Добавить на главную*</p>
                        <div class="col-xs-4 col-sm-10 shift-checkbox1 shift-checkbox2">
                            <div class="input-group form_element">
                                <div class="">
                                    <input type="checkbox" value="1" class="form-control" id="is_promotion"
                                           name="is_promotion"
                                           @if($article["is_promotion"] ?? false)
                                           checked="checked"
                                        @endif
                                    >
                                    <label for="is_promotion"></label>
                                </div>
                            </div>
                        </div>
                        </div>

                        <label class="col-sm-3 control-label" for="form-control-1">Название*</label>
                        <div class="col-sm-9">
                            <input id="name" class="form-control" name="name" value="{{ $article["name"] ?? '' }}" type="text" >
                        </div>

                        <label class="col-sm-3 control-label" for="form-control">Содержание*</label>
                        <div class="col-sm-9">
                            <textarea id="content" class="form-control"
                                      name="content">{{ $article["content"] ?? false}}</textarea>
                        </div>

                        <label class="col-sm-3 control-label">Категория*</label>
                        <div class="col-xs-4 col-sm-3">
                            <select class="custom-select" name="category_id" id="category" >
                                @foreach($categories as $category)
                                    <option  @if($update ?? false)
                                                @if (old('category_id', $article->category_id) == $category["id"])
                                                    selected="selected"
                                                @endif
                                             @endif value="{{ $category["id"] }}" >{{ $category["name"] }}</option>
                                @endforeach
                            </select>
                        </div>

                        <label class="col-sm-3 control-label shift-products">Продукты*</label>
                        <div class="col-xs-4 col-sm-3">
                            <select class="custom-select js-example-basic-multiple" multiple="multiple" name="products" id="products" >
                                @foreach($categories as $category)
                                    <optgroup label="{{ $category['name'] }}">
                                        @foreach($category->products as $product)
                                                <option
                                                    @if($update ?? false)
                                                        @if( in_array($product->id, $chosen_products))
                                                            selected="selected"
                                                        @endif
                                                    @endif
                                                        id="product_id" name="product_id" value="{{ $product["id"]}}">{{ $product["name"] }}</option>
                                        @endforeach
                                    </optgroup>
                                @endforeach
                            </select>
                        </div>

                        <label class="col-sm-3 control-label">Изображения*</label>
                        <div class="col-sm-9 form_element">
                            <label id="images_label" class="drive-uploader-btn btn btn-primary btn-lg"
                                   @if($article['image'] ?? false)
                                   disabled
                                @endif>
                                Выбрать файл
                                <input class="drive-uploader-input" type="file" name="files" id="files"
                                       @if($article['image'] ?? false)
                                       disabled
                                    @endif/>
                            </label>
                        </div>

                        <div class="col-sm-10">
                            <div id="images_list">
                                @if($article['image'] ?? false)
                                    <div class="listImg">
                                        <button id="imgButton" data-id="{{ $article['image'] }}" >Удалить</button>
                                        <img src="{{ asset( $article['image']) }}" width="130px"/>
                                    </div>
                                @endif
                            </div>
                        </div>

                        <label class="col-sm-3 control-label" for="form-control-1">Подпись к картинке</label>
                        <div class="col-sm-9">
                            <input id="image_caption" class="form-control" name="image_caption" value="{{ $article["image_caption"] ?? '' }}" type="text" >
                        </div>

                        <label class="col-sm-3 control-label" for="form-control-1"></label>
                        <div class="col-sm-12" align="right">
                            <label class="btn btn-success file-upload-btn">
                                @if($update ?? false)
                                    Изменить
                                @else
                                    Добавить
                                @endif
                                <input class="file-upload-input" type="submit" multiple="">
                            </label>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{{ asset("js/resources/cropped.js") }}"></script>
    <script type="text/javascript" src="{{ asset("js/resources/articles.js") }}"></script>
@endsection

resources/views/admin/articles/list.blade.php
@extends('layouts.admin_app')

@section('content')
    <div class="title-bar">
        <h1 class="title-bar-title">
            <span class="d-ib">Статьи</span>
        </h1>
    </div>
    @if (session('success'))
        <div class="alert alert-success" role="alert">
            {{ session('success') }}
        </div>
    @endif
    <a href="{{ route("admin.articles.create") }}" class="btn btn-primary btn-lg btn-warning">Добавить статью</a>
    <div class="row">
        <div class="col-xs-12">
            <div class="panel">
                <div class="panel-body">
                    <div class="table-responsive">
                        <table id="demo-dynamic-tables-1" class="table table-middle nowrap">
                            <thead>
                            <tr>
                                <th>
                                    #
                                </th>
                                <th>Акция</th>
                                <th>Название статьи</th>
                                <th>Содержание статьи</th>
                                <th>Дата создания</th>
                                <th>Дата изменения</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($articles as $article)
                                <tr>
                                    <td>
                                        {{ $loop->iteration + ($articles->currentpage() - 1) * $articles->perpage() }}
                                    </td>
                                    <td>
                                        <strong>{{ $article["is_promotion"] }}</strong>
                                    </td>
                                    <td>
                                        <strong>{{ $article["name"] }}</strong>
                                    </td>
                                    <td>
                                        <p>{{ $article["content"] }}</p>
                                    </td>
                                    <td class="maw-320">
                                        <strong>{{ $article["created_at"] }} </strong>
                                    </td>
                                    <td>
                                        {{ $article["updated_at"] }}
                                    </td>
                                    <td>
                                        <div class="btn-group pull-right dropdown">
                                            <button class="btn btn-link link-muted" aria-haspopup="true"
                                                    data-toggle="dropdown" type="button">
                                                <span class="icon icon-ellipsis-h icon-lg icon-fw"></span>
                                            </button>
                                            <ul class="dropdown-menu dropdown-menu-right">
                                                <li>
                                                    <a href="{{ route("admin.articles.edit", ["id_article" => $article["id"]]) }}">Изменить</a>
                                                </li>
                                                <li>
                                                    <a href="" class="delete_btn">
                                                        Удалить
                                                        <form class="hidden_form" method="post"
                                                              action="{{ route("admin.articles.destroy", ["id_article" => $article["id"]]) }}">
                                                            @csrf
                                                            @method("DELETE")
                                                        </form>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="dataTables_paginate paging_simple_numbers" id="demo-dynamic-tables-2_paginate">
                                {{ $articles->links('admin.pagination.default') }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection