routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Product;
use Symfony\Component\Console\Input\Input;

Route::pattern('id_slider', '[0-9]+');
Route::pattern('id_category', '[0-9]+');
Route::pattern('id_brand', '[0-9]+');
Route::pattern('id_basket', '[0-9]+');
Route::pattern('id_product', '[0-9]+');
Route::pattern('id_promocode', '[0-9]+');

//URL::forceScheme('https');
Route::post('/ajax_login', 'Auth\LoginController@ajaxLogin')->name("ajax_login");
Auth::routes();


Route::get('/', 'MainPageController@main')->name("home");
Route::get('/yml', 'YmlController@index')->name("sitemap");
Route::get('/content/{slug}', 'SiteRedirectController@redirect');

Route::group(['prefix' => 'blocks', 'as' => 'blocks.'], function () {
    Route::get("/popular_products", "MainPageController@popularProducts")->name("popular_products");
    Route::get("/products_category/{id}", "MainPageController@productsCategory")->name("products_category");
});

/* Static Pages routing */
Route::prefix('page')->group(function () {
    Route::get('/contact', 'StaticPagesController@contact')->name('contact');
    Route::get('/shipping', 'StaticPagesController@shipping')->name('shipping');
    Route::get('/gifts', 'StaticPagesController@gifts')->name('gifts');
    Route::get('/price_list', 'StaticPagesController@priceList')->name('price_list');
    Route::get('/cooperation', 'StaticPagesController@cooperation')->name('cooperation');
    Route::get('/job_offers', 'StaticPagesController@jobOffers')->name('job_offers');
    Route::get('/purchase_rules', 'StaticPagesController@purchaseRules')->name('purchase_rules');
});

Route::group([], function () {
    Route::get('/search', 'SearchController@index')->name('search');

    Route::group(['as' => 'payments.', 'prefix' => 'payments'], function () {
        Route::get('/success', 'PaymentsController@success')->name('success');
        Route::get('/error', 'PaymentsController@error')->name('error');
    });

    Route::group(['as' => 'orders.', 'prefix' => 'order'], function () {
        Route::post('/', 'OrdersController@store')->name('store');
        Route::post('/one_click', 'OrdersController@byOneClick')->name('by_one_click');
    });

    Route::group(['as' => 'user.', 'prefix' => 'user'], function () {
        Route::get('/edit', 'UsersController@edit')->name('user.edit');
    });

    Route::group(['as' => 'news.', 'prefix' => 'news'], function () {
        Route::get('/', 'ArticlesController@index')->name('index');
        Route::get('/{id}', 'ArticlesController@show')->name('show');
    });

    Route::group(['as' => 'categories.', 'prefix' => 'categories'], function () {
        Route::get('/', 'CategoriesController@index')->name('index');
        Route::get('/products', 'CategoriesController@getProducts')->name("products");
        Route::get('/filters/{slug}', 'CategoriesController@filters')->name("filters");
        Route::get('/{slug}', 'CategoriesController@show')->name("page");
    });

    Route::group(['as' => 'products.', 'prefix' => 'products'], function () {
        Route::get('/{slug}/{size?}/{color?}', 'ProductsController@show')->name("page");
    });

    Route::group(['as' => 'likes.', 'prefix' => 'likes'], function () {
        Route::get('/', 'LikesController@index')->name("index");
        Route::post('/', 'LikesController@store')->name("store");
        Route::delete('/', 'LikesController@destroy')->name("destroy");
    });

    Route::group(['as' => 'comments.', 'prefix' => 'comments'], function () {
        Route::get('/{product_id}', 'CommentsController@index')->name("index");
        Route::post('/{product_id}', 'CommentsController@store')->name("store");
    });

    Route::group(['as' => 'baskets.', 'prefix' => 'baskets'], function () {
        Route::get('/', 'BasketsController@index')->name('index');
        Route::get('/data', 'BasketsController@getData')->name('get_data');
        Route::put('/{product_id}', 'BasketsController@update')->name('update');
        Route::post('/', 'BasketsController@store')->name('store');
        Route::delete('/{product_id?}', 'BasketsController@destroy')->name('destroy');
    });
});

Route::group(['prefix' => 'admin1', 'as' => 'admin.'], function () {
    Route::get("statistics", "Admin\StatisticsController@getStatistics");
    Route::get("orders", "Admin\OrdersController@index");
    Route::get("brands", "Admin\BrandsController@index");
    Route::get("categories", "Admin\CategoriesController@index");
    Route::get("users", "Admin\UsersController@index");
});

/* Admin routing */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware'=>['auth', 'role:admin']], function () {
    Route::get('/', 'StaticPagesController@admin')->name("main");

    Route::group(['as' => 'charts.', 'prefix' => 'charts'], function () {
        Route::get('/orders_for_registered_or_not', 'Admin\ChartsController@ordersForRegisteredOrNot')->name('orders_for_registered_or_not');
        Route::get('/avg_orders_sum', 'Admin\ChartsController@avgOrdersSum')->name('avg_orders_sum');
        Route::get('/statistics_per_month', 'Admin\ChartsController@statisticsPerMonth')->name('statistics_per_month');
    });


    Route::resource('/products', 'Admin\ProductsController', [
        'names' => [
            'index' => 'products.index',
            'show' => 'products.show',
            'create' => 'products.create',
            'update' => 'products.update',
            'edit' => 'products.edit',
            'store' => 'products.store',
            'destroy' => 'products.destroy',
        ],
        'parameters' => [
            'products' => 'id_product'
        ]
    ]);

    Route::resource('/brands', 'Admin\BrandsController', [
        'names' => [
            'index' => 'brands.index',
            'create' => 'brands.create',
            'update' => 'brands.update',
            'edit' => 'brands.edit',
            'store' => 'brands.store',
            'destroy' => 'brands.destroy',
        ],
        'parameters' => [
            'brands' => 'id_brand'
        ]
    ])->except('show');

    Route::resource('/categories', 'Admin\CategoriesController', [
        'names' => [
            'index' => 'categories.index',
            'create' => 'categories.create',
            'update' => 'categories.update',
            'edit' => 'categories.edit',
            'store' => 'categories.store',
            'destroy' => 'categories.destroy',
        ],
        'parameters' => [
            'categories' => 'id_category'
        ]
    ])->except('show');

    Route::resource('/comments', 'Admin\CommentsController', [
        'name' => [
            'index' => 'comments.index',
            'update' => 'comments.update',
            'destroy' => 'comments.destroy',
        ],
        'parameters' => [
            'comments' => 'id_comment',
        ]
    ])->except(['show', 'create', 'edit', 'store']);

    Route::resource('/delivery_types', 'Admin\DeliveryTypesController', [
        'name' => [
            'index' => 'delivery_types.index',
            'create' => 'delivery_types.create',
            'update' => 'delivery_types.update',
            'edit' => 'delivery_types.edit',
            'store' => 'delivery_types.store',
            'destroy' => 'delivery_types.destroy',
        ],
        'parameters' => [
            'delivery_types' => 'id_delivery_type',]
    ])->except('show');


    Route::resource('/slider', 'Admin\SliderController', [
        'names' => [
            'create' => 'slider.create',
            'store' => 'slider.store',
            'update' => 'slider.update',
            'edit' => 'slider.edit',
            'destroy' => 'slider.destroy',
        ],
        'parameters' => [
            'slider' => 'id_slider'
        ]
    ])->except(['show']);

    Route::resource('/users', 'Admin\UsersController', [
        'names' => [
            'index' => 'users.index',
            'create' => 'users.create',
            'store' => 'users.store',
            'edit' => 'users.edit',
            'update' => 'users.update',
            'destroy' => 'users.destroy'
        ],
        'parameters' => [
            'users' => 'id_user'
        ]
    ])->except('show');
    Route::put('/users/{id_user}/edit', 'Admin\UsersController@updatePassword')->name('users.update_password');

    Route::resource('/articles', 'Admin\ArticlesController', [
        'names' => [
            'index' => 'articles.index',
            'create' => 'articles.create',
            'update' => 'articles.update',
            'edit' => 'articles.edit',
            'store' => 'articles.store',
            'destroy' => 'articles.destroy',
        ],
        'parameters' => [
            'articles' => 'id_article'
        ]
    ])->except('show');

    Route::resource('/promocodes', 'Admin\PromocodesController', [
        'name' => [
            'index' => 'promocodes.index',
            'create' => 'promocodes.create',
            'update' => 'promocodes.update',
            'edit' => 'promocodes.edit',
            'store' => 'promocodes.store',
            'destroy' => 'promocodes.destroy',
        ],
        'parameters' => [
            'promocodes' => 'id_promocode',
        ]
    ])->except('show');

    Route::resource('/orders', 'Admin\OrdersController', [
        'name' => [
            'index' => 'orders.index',
            'show' => 'orders.show',
            'create' => 'orders.create',
            'update' => 'orders.update',
            'edit' => 'orders.edit',
            'store' => 'orders.store',
            'destroy' => 'orders.destroy',
        ],
        'parameters' => [
            'orders' => 'id_order',
        ]

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\SiteController;
use Dobro\MoySkladApi\Facades\ProductFolder;
use Exception;
use Illuminate\Contracts\Routing\ResponseFactory;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Illuminate\View\View;

/**
 * Class CategoriesController
 * @package App\Http\Controllers
 */
class CategoriesController extends SiteController
{
    private $categoriesInPage = 10;

    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $categories = Category::orderBy("name")->paginate($this->categoriesInPage);
//        return $this->renderOutputAdmin("admin.categories.list", [
//            "categories" => $categories
//        ]);
        return $categories;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        return $this->renderOutputAdmin("admin.categories.form", [
            "route" => route("admin.categories.store")
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'is_on_main' => 'boolean',
            'description' => 'required'
        ]);

        if ($validator->fails()) {
            return response()->json(['mess' => $validator->errors()->all(), 'success' => false], 400);
        }

        $userUploadedImg = $this->loadImages(json_decode($request->images), null, 600);

        if (sizeof($userUploadedImg) > 1) {
            $data["success"] = false;
            $data["mess"] = "Допустимое количество изображений - не более одного";
            return response()->json($data, 400);
        }

        $categorySklad = ProductFolder::create([
            "name" => $request->name,
            "description" => $request->description
        ]);

        Category::create([
            'name' => $request->name,
            'description' => $request->description,
            'is_on_main' => $request->input("is_on_main", false),
            'image' => $userUploadedImg[0],
            'slug' => Str::slug($request->name, "_"),
            'moy_sklad_id' => $categorySklad->id
        ])->id;

        return response()->json(['mess' => "Категория успешно добавлена", 'success' => true], 200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Factory|View
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return $this->renderOutputAdmin("admin.categories.form", [
            "category" => $category,
            "route" => route("admin.categories.update", ["id_category" => $id]),
            "update" => true
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return JsonResponse
     * @throws Exception
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'images' => 'required'
        ]);

        if ($validator->fails()) {
            return response()->json(['mess' => $validator->errors()->first(), 'success' => true], 400);
        }

        $categoryArr = [
            'name' => $request->name,
            'description' => $request->description,
            'is_on_main' => $request->input("is_on_main", false),
            'slug' => Str::slug($request->name, "_")
        ];

        $images = json_decode($request->images, true);

        if (!is_int($images[0])) {
            $userUploadedImg = $this->loadImages($images, 800, null);
            $categoryArr["image"] = $userUploadedImg[0];
        }

        Category::whereId($id)->update($categoryArr);

        ProductFolder::where("id", "=", (string)$request->category_sklad_id)->update([
            "name" => $request->name,
            "description" => $request->description
        ]);

        return response()->json(['mess' => "Категория успешно изменена", 'success' => true], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return void
     * @throws Exception
     */
    public function destroy($id)
    {
        $cetagory = Category::select("moy_sklad_id")->where("id", $id)->first();
        try {
            Category::whereId($id)->delete();
        } catch (\ErrorException $e) {
        }
        ProductFolder::where("id", "=", (string)$cetagory->moy_sklad_id)->delete();
        return redirect()->route("admin.categories.index")->withSuccess("Категория успешно удалена");
    }

    /**
     * Sorted categories.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function sortable(Request $request)
    {
        $categories = $request->sortable;

        foreach ($categories as $id => $position) {
            Category::whereId($id)->update(['position' => $position]);
        }

        $data["success"] = true;
        $data["mess"] = "Обновлено";
        return response()->json($data);
    }
}

resources/views/admin/categories/form.blade.php
@extends('layouts.admin_app')

@section('content')
    <div class="title-bar">
        <h1 class="title-bar-title">
            <span class="d-ib">
                @if($update ?? false)
                    Изменить категорию
                @else
                    Добавить категорию
                @endif
            </span>
        </h1>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="demo-form-wrapper">
                @if (session('errors'))
                    <div class="alert alert-danger" role="alert">
                        {{ session('errors')->first() }}
                    </div>
                @endif

                <form class="form form-horizontal create_category" action="{{ $route }}" method="post">
                    <input type="hidden" id="update" value="{{ $update ?? false }}">
                    <input type="hidden" id="id_category" value="{{ $category->id ?? false }}">
                    <input type="hidden" id="category_sklad_id" value="{{ $category->moy_sklad_id ?? false}}">
                    <div class="form-group">
                        <label class="col-sm-1 control-label" for="form-control-1">Название</label>
                        <div class="col-sm-12">
                            <input id="name" class="form-control" name="name" value="{{ $category->name ?? '' }}"
                                   type="text">
                        </div>

                        <label class="col-sm-1 control-label">Описание</label>
                        <div class="col-sm-12">
                            <textarea name="description" id="description"
                                      class="form-control form_element">{{ $category->description ?? '' }}</textarea>
                        </div>

                        <div class="label-for-admin">
                            <p class="col-sm-4 control-label">Добавить на главную</p>
                            <div class="col-xs-4 col-sm-10 shift-checkbox1">
                                <div class="input-group form_element">
                                    <div class="">
                                        <input type="checkbox" value="1" class="" id="is_on_main"
                                               name="is_on_main"
                                               @if($category->is_on_main ?? false)
                                               checked="checked"
                                            @endif
                                        >
                                        <label for="is_on_main"></label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <label class="col-sm-3 control-label">Изображения</label>

                        <div class="col-sm-12">
                            <div id="images_list">
                                @if($category['image'] ?? false)
                                    <div class="listImg">
                                        <button id="imgButton" data-id="{{ $category['id'] }}" >Удалить</button>
                                        <img src="{{ asset("/uploads/mini/".$category['image']) }}" width="130px"/>
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-sm-4 form_element select-file-button">
                            <label id="images_label" class="drive-uploader-btn btn btn-primary btn-lg"
                                   @if($category['image'] ?? false)
                                   disabled
                                @endif>
                                Выбрать файл
                                <input class="drive-uploader-input" type="file" name="files" id="files"
                                       @if($category['image'] ?? false)
                                       disabled
                                    @endif/>
                            </label>
                        </div>

                        <label class="col-sm-3 control-label" for="form-control-1"></label>
                        <div class="col-sm-3" align="right">
                            <label class="btn btn-success file-upload-btn shift-select-img shift-img-left">
                                @if($update ?? false)
                                    Изменить
                                @else
                                    Добавить
                                @endif
                                <input class="file-upload-input" type="submit" multiple="">
                            </label>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{{ asset("js/resources/cropped.js") }}"></script>
    <script type="text/javascript" src="{{ asset("js/resources/categories.js") }}"></script>
@endsection

resources/views/admin/categories/list.blade.php
@extends('layouts.admin_app')

@section('content')
    <div class="title-bar">
        <h1 class="title-bar-title">
            <span class="d-ib">Категории</span>
        </h1>
    </div>
    @if (session('success'))
        <div class="alert alert-success" role="alert">
            {{ session('success') }}
        </div>
    @endif
    <a href="{{ route("admin.categories.create") }}" class="btn btn-primary btn-lg btn-warning">Добавить категорию</a>
    <div class="row">
        <div class="col-xs-12">
            <div class="panel">
                <div class="panel-body">
                    <div class="table-responsive">
                        <table id="demo-dynamic-tables-1" class="table table-middle nowrap">
                            <thead>
                            <tr>
                                <th>
                                    #
                                </th>
                                <th>Название категории</th>
                                <th>Дата создания</th>
                                <th>Дата изменения</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    <td>
                                        {{ $loop->iteration + ($categories->currentpage() - 1) * $categories->perpage() }}
                                    </td>
                                    <td>
                                        <strong>{{ $category["name"] }}</strong>
                                    </td>
                                    <td class="maw-320">
                                        {{ $category["created_at"] }}
                                    </td>
                                    <td>{{ $category["updated_at"] }}</td>
                                    <td>
                                        <div class="btn-group pull-right dropdown">
                                            <button class="btn btn-link link-muted" aria-haspopup="true" data-toggle="dropdown" type="button">
                                                <span class="icon icon-ellipsis-h icon-lg icon-fw"></span>
                                            </button>
                                            <ul class="dropdown-menu dropdown-menu-right">
                                                <li><a href="{{ route("admin.categories.edit", ["id_category" => $category["id"]]) }}">Изменить</a></li>
                                                <li>
                                                    <a href="" class="delete_btn">
                                                        Удалить
                                                        <form class="hidden_form" method="post" action="{{ route("admin.categories.destroy", ["id_category" => $category["id"]]) }}">
                                                            @csrf
                                                            @method("DELETE")
                                                        </form>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="dataTables_paginate paging_simple_numbers" id="demo-dynamic-tables-2_paginate">
                                {{ $categories->links('admin.pagination.default') }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection