routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Product;
use Symfony\Component\Console\Input\Input;

Route::pattern('id_slider', '[0-9]+');
Route::pattern('id_category', '[0-9]+');
Route::pattern('id_brand', '[0-9]+');
Route::pattern('id_basket', '[0-9]+');
Route::pattern('id_product', '[0-9]+');
Route::pattern('id_promocode', '[0-9]+');

//URL::forceScheme('https');
Route::post('/ajax_login', 'Auth\LoginController@ajaxLogin')->name("ajax_login");
Auth::routes();


Route::get('/', 'MainPageController@main')->name("home");
Route::get('/yml', 'YmlController@index')->name("sitemap");
Route::get('/content/{slug}', 'SiteRedirectController@redirect');

Route::group(['prefix' => 'blocks', 'as' => 'blocks.'], function () {
    Route::get("/popular_products", "MainPageController@popularProducts")->name("popular_products");
    Route::get("/products_category/{id}", "MainPageController@productsCategory")->name("products_category");
});

/* Static Pages routing */
Route::prefix('page')->group(function () {
    Route::get('/contact', 'StaticPagesController@contact')->name('contact');
    Route::get('/shipping', 'StaticPagesController@shipping')->name('shipping');
    Route::get('/gifts', 'StaticPagesController@gifts')->name('gifts');
    Route::get('/price_list', 'StaticPagesController@priceList')->name('price_list');
    Route::get('/cooperation', 'StaticPagesController@cooperation')->name('cooperation');
    Route::get('/job_offers', 'StaticPagesController@jobOffers')->name('job_offers');
    Route::get('/purchase_rules', 'StaticPagesController@purchaseRules')->name('purchase_rules');
});

Route::group([], function () {
    Route::get('/search', 'SearchController@index')->name('search');

    Route::group(['as' => 'payments.', 'prefix' => 'payments'], function () {
        Route::get('/success', 'PaymentsController@success')->name('success');
        Route::get('/error', 'PaymentsController@error')->name('error');
    });

    Route::group(['as' => 'orders.', 'prefix' => 'order'], function () {
        Route::post('/', 'OrdersController@store')->name('store');
        Route::post('/one_click', 'OrdersController@byOneClick')->name('by_one_click');
    });

    Route::group(['as' => 'user.', 'prefix' => 'user'], function () {
        Route::get('/edit', 'UsersController@edit')->name('user.edit');
    });

    Route::group(['as' => 'news.', 'prefix' => 'news'], function () {
        Route::get('/', 'ArticlesController@index')->name('index');
        Route::get('/{id}', 'ArticlesController@show')->name('show');
    });

    Route::group(['as' => 'categories.', 'prefix' => 'categories'], function () {
        Route::get('/', 'CategoriesController@index')->name('index');
        Route::get('/products', 'CategoriesController@getProducts')->name("products");
        Route::get('/filters/{slug}', 'CategoriesController@filters')->name("filters");
        Route::get('/{slug}', 'CategoriesController@show')->name("page");
    });

    Route::group(['as' => 'products.', 'prefix' => 'products'], function () {
        Route::get('/{slug}/{size?}/{color?}', 'ProductsController@show')->name("page");
    });

    Route::group(['as' => 'likes.', 'prefix' => 'likes'], function () {
        Route::get('/', 'LikesController@index')->name("index");
        Route::post('/', 'LikesController@store')->name("store");
        Route::delete('/', 'LikesController@destroy')->name("destroy");
    });

    Route::group(['as' => 'comments.', 'prefix' => 'comments'], function () {
        Route::get('/{product_id}', 'CommentsController@index')->name("index");
        Route::post('/{product_id}', 'CommentsController@store')->name("store");
    });

    Route::group(['as' => 'baskets.', 'prefix' => 'baskets'], function () {
        Route::get('/', 'BasketsController@index')->name('index');
        Route::get('/data', 'BasketsController@getData')->name('get_data');
        Route::put('/{product_id}', 'BasketsController@update')->name('update');
        Route::post('/', 'BasketsController@store')->name('store');
        Route::delete('/{product_id?}', 'BasketsController@destroy')->name('destroy');
    });
});

Route::group(['prefix' => 'admin1', 'as' => 'admin.'], function () {
    Route::get("statistics", "Admin\StatisticsController@getStatistics");
    Route::get("orders", "Admin\OrdersController@index");
    Route::get("brands", "Admin\BrandsController@index");
    Route::get("categories", "Admin\CategoriesController@index");
    Route::get("users", "Admin\UsersController@index");
});

/* Admin routing */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware'=>['auth', 'role:admin']], function () {
    Route::get('/', 'StaticPagesController@admin')->name("main");

    Route::group(['as' => 'charts.', 'prefix' => 'charts'], function () {
        Route::get('/orders_for_registered_or_not', 'Admin\ChartsController@ordersForRegisteredOrNot')->name('orders_for_registered_or_not');
        Route::get('/avg_orders_sum', 'Admin\ChartsController@avgOrdersSum')->name('avg_orders_sum');
        Route::get('/statistics_per_month', 'Admin\ChartsController@statisticsPerMonth')->name('statistics_per_month');
    });


    Route::resource('/products', 'Admin\ProductsController', [
        'names' => [
            'index' => 'products.index',
            'show' => 'products.show',
            'create' => 'products.create',
            'update' => 'products.update',
            'edit' => 'products.edit',
            'store' => 'products.store',
            'destroy' => 'products.destroy',
        ],
        'parameters' => [
            'products' => 'id_product'
        ]
    ]);

    Route::resource('/brands', 'Admin\BrandsController', [
        'names' => [
            'index' => 'brands.index',
            'create' => 'brands.create',
            'update' => 'brands.update',
            'edit' => 'brands.edit',
            'store' => 'brands.store',
            'destroy' => 'brands.destroy',
        ],
        'parameters' => [
            'brands' => 'id_brand'
        ]
    ])->except('show');

    Route::resource('/categories', 'Admin\CategoriesController', [
        'names' => [
            'index' => 'categories.index',
            'create' => 'categories.create',
            'update' => 'categories.update',
            'edit' => 'categories.edit',
            'store' => 'categories.store',
            'destroy' => 'categories.destroy',
        ],
        'parameters' => [
            'categories' => 'id_category'
        ]
    ])->except('show');

    Route::resource('/comments', 'Admin\CommentsController', [
        'name' => [
            'index' => 'comments.index',
            'update' => 'comments.update',
            'destroy' => 'comments.destroy',
        ],
        'parameters' => [
            'comments' => 'id_comment',
        ]
    ])->except(['show', 'create', 'edit', 'store']);

    Route::resource('/delivery_types', 'Admin\DeliveryTypesController', [
        'name' => [
            'index' => 'delivery_types.index',
            'create' => 'delivery_types.create',
            'update' => 'delivery_types.update',
            'edit' => 'delivery_types.edit',
            'store' => 'delivery_types.store',
            'destroy' => 'delivery_types.destroy',
        ],
        'parameters' => [
            'delivery_types' => 'id_delivery_type',]
    ])->except('show');


    Route::resource('/slider', 'Admin\SliderController', [
        'names' => [
            'create' => 'slider.create',
            'store' => 'slider.store',
            'update' => 'slider.update',
            'edit' => 'slider.edit',
            'destroy' => 'slider.destroy',
        ],
        'parameters' => [
            'slider' => 'id_slider'
        ]
    ])->except(['show']);

    Route::resource('/users', 'Admin\UsersController', [
        'names' => [
            'index' => 'users.index',
            'create' => 'users.create',
            'store' => 'users.store',
            'edit' => 'users.edit',
            'update' => 'users.update',
            'destroy' => 'users.destroy'
        ],
        'parameters' => [
            'users' => 'id_user'
        ]
    ])->except('show');
    Route::put('/users/{id_user}/edit', 'Admin\UsersController@updatePassword')->name('users.update_password');

    Route::resource('/articles', 'Admin\ArticlesController', [
        'names' => [
            'index' => 'articles.index',
            'create' => 'articles.create',
            'update' => 'articles.update',
            'edit' => 'articles.edit',
            'store' => 'articles.store',
            'destroy' => 'articles.destroy',
        ],
        'parameters' => [
            'articles' => 'id_article'
        ]
    ])->except('show');

    Route::resource('/promocodes', 'Admin\PromocodesController', [
        'name' => [
            'index' => 'promocodes.index',
            'create' => 'promocodes.create',
            'update' => 'promocodes.update',
            'edit' => 'promocodes.edit',
            'store' => 'promocodes.store',
            'destroy' => 'promocodes.destroy',
        ],
        'parameters' => [
            'promocodes' => 'id_promocode',
        ]
    ])->except('show');

    Route::resource('/orders', 'Admin\OrdersController', [
        'name' => [
            'index' => 'orders.index',
            'show' => 'orders.show',
            'create' => 'orders.create',
            'update' => 'orders.update',
            'edit' => 'orders.edit',
            'store' => 'orders.store',
            'destroy' => 'orders.destroy',
        ],
        'parameters' => [
            'orders' => 'id_order',
        ]

resources/views/pages/contact.blade.php
@extends('layouts.app')

@section('content')
<div class="contact_map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2244.637184209241!2d37.55589611608901!3d55.76480459853347!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46b5497ee2cbec7b%3A0xc68a2ac8c69f2def!2z0K3Qu9C10LrRgtGA0L7QvdC40LrQsCDQvdCwINCf0YDQtdGB0L3QtQ!5e0!3m2!1sru!2sru!4v1570174883201!5m2!1sru!2sru"
            frameborder="0" allowfullscreen=""></iframe>
    <div class="contact_info">

        {{  Breadcrumbs:: render("pages.contact")}}

        <div class="block-head">
            <p class="h2 category__title">Контакты</p>
            <img class="category__wave address__description" src="{{ asset("images/wave.png") }}" alt="">
        </div>
        <p class="contact_info_text contact-sec"><span class="contact_info_text_bold">Номера телефонов</span><br>
            <a href="tel:+74955178871" class="text-style-contact">+7 (495) 517-88-71</a><br>
            <a href="tel:+74955064952" class="text-style-contact">+7 (495) 506-49-52</a><br><br>
            <span class="contact_info_text_bold">Электронная почта</span><br>
            <a class="text-style-contact">mail@chistokot.ru</a><br>
        </p>
        <div class="block-head">
            <p class="h2 category__title">Адрес магазина</p>
            <img class="category__wave address__description" src="{{ asset("images/wave.png") }}" alt="">
        </div>
        <div class="contact_info_store_address">
            <p class="contact_info_text"><span class="contact_info_text_bold">Станция метро</span></p>
            <p class="contact_info_text"> Метро "Улица 1905 года"</p>
            <p class="contact_info_text "><span class="contact_info_text_bold">Адрес магазина</span></p>
            <p class="contact_info_text"> Москва, Звенигородское шоссе, д. 4, торговый центр
                "Электроника на Пресне", желтая линия, стенд Б-12</p>
            <p class="contact_info_text"><span class="contact_info_text_bold">Режим работы</span></p>
            <p class="contact_info_text"> Ежедневно с 10:00 до 20:00</p>
            <p class="contact_info_text"><span class="contact_info_text_bold">Как добраться</span></p>
            <p class="contact_info_text"> Метро "Улица 1905 года", первый вагон из центра, выход на
                левую сторону, пройти до пересечения улицы 1905
                года со Звенигородским шоссе, повернуть направо и через 150 метров с правой стороны вход на территорию
                торгового центра. Удобный подъезд со стороны нового восьмиполосного Звенигородского шоссе обеспечит
                максимум
                удобства покупателям, приехавшим на личном транспорте.</p>
        </div>
    </div>
</div>

@endsection

resources/views/pages/cooperation.blade.php
@extends('layouts.app')

@section('content')
    <h1>
        Здесь будет раздел 'Сотрудничество'
    </h1>
@endsection

resources/views/pages/gifts.blade.php
@extends('layouts.app')

@section('content')
    <h1>
        Здесь будет раздел ПОДАРКИ
    </h1>
@endsection

resources/views/pages/job_offers.blade.php
@extends('layouts.app')

@section('content')
    <h1>
        Здесь будет раздел 'Вакансии'
    </h1>
@endsection

resources/views/pages/main_page.blade.php
@extends('layouts.app')

@section('content')
    <main-slider-component :slides="{{ json_encode($sliders) }}"></main-slider-component>

    <section class="content-section">
        <div class="container justify-content-center">
            <div class="text-center category__block description-carousel">
                <p class="h2 category__title">Категории</p>
                <img class="category__wave" src="{{ asset("images/wave.png")}}" alt="">
                <p class="category__description">Ознакомтесь с нашим огромным выбором товаров!</p>
            </div>
            <categories-slider-component :categories="{{ json_encode($categories) }}"></categories-slider-component>
        </div>
    </section>

    <section class="content-section">
        <div class="container justify-content-center">
            <div class="text-center category__link-block follow-to-catalog">
                <a href="{{ route("categories.index") }}">
                    Перейти к каталогу <img src="{{ asset("images/a-main-page.png") }}" alt="" style="max-width: 5px;">
                </a>
            </div>

            <div class="text-center category__block description-carousel">
                <p class="h2 category__title">Популярные товары</p>
                <img class="category__wave" src="{{ asset("images/wave.png") }}" alt="">
                <p class="category__description">Самые популярные товары, которые зарекомендовали себя у наших
                    клиентов!</p>
            </div>

            <product-list-slider-component route_e="blocks.popular_products"></product-list-slider-component>

            <div class="text-center category__link-block follow-to-catalog">
                <a href="{{ route("categories.index") }}">
                    <p>Перейти к каталогу
                        <img src="{{ asset("images/a-main-page.png") }}" alt="">
                    </p>
                </a>
            </div>
        </div>
    </section>

    @if (count($promotions))
        <section class="container content-section promo justify-content-center">
            <div class="text-center category__block">
                <p class="h2 category__title">Акции</p>
                <img class="category__wave" src="{{ asset("images/wave.png") }}" alt="">
                <p class="category__description">Мы всегда производим акции на все товары в нашем ассортименте!</p>
            </div>
            <div class="sale-flexbox category__block">
                @foreach($promotions as $promotion)
                    <a href="{{ route('news.show', $promotion['id']) }}" class="one-sale">
                        <p>{{ $promotion['name'] }}</p>
                        <img class="sale-img" src="{{ asset($promotion['image']) }}" alt="">
                    </a>
                @endforeach
            </div>
        </section>
    @endif

    <section>
        @include('partials.subscription_sale')
    </section>


    @foreach($categories_info as $category_info)
        <section class="content-section">
            <div class="container justify-content-center">
                <div class="text-center category__block">
                    <p class="h2 category__title">{{ $category_info->name }}</p>
                    <img class="category__wave" src="{{ asset("images/wave.png") }}" alt="">
                </div>

                <product-list-slider-component route_e="blocks.products_category" :category_id="{{ $category_info->id }}"></product-list-slider-component>

                <div class="text-center category__link-block follow-to-catalog">
                    <a href="{{ route("categories.page", ["slug" => $category_info->slug]) }}">
                        <p>
                            Перейти к категории <img src="{{ asset("images/a-main-page.png") }}" alt=""
                                                     style="max-width: 5px;">
                        </p>
                    </a>
                </div>
            </div>

        </section>
    @endforeach

    @include('partials.about')
@endsection

resources/views/pages/price_list.blade.php
@extends('layouts.app')

@section('content')
    <h1>
        Здесь будет раздел 'Прайс-лист'
    </h1>
@endsection

resources/views/pages/purchase_rules.blade.php
@extends('layouts.app')

@section('content')
    <h1>
        Здесь будет раздел 'Правила покупки'
    </h1>
@endsection

resources/views/pages/shipping.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="basket_first_column">
            {{  Breadcrumbs:: render("pages.shipping")}}

            <div class="block-head">
                <p class="h2 category__title">Доставка</p>
                <img class="category__wave address__description" src="imgs/wave.png" alt="">
            </div>
            <p class="shipping_first_column_text"> Заказ товаров на дом и в офис осуществляется с 9.00 до 20.00 через
                интернет-магазин по адресу ChistoKot.ru, или по телефонам 8 (495) 517-88-71, 8 (495) 506-49-52.</p>
            <h4>Стоимость доставки</h4>
            <p class="shipping_first_column_text">
                <ul class="shipping_first_column_text">
                    <p>
                        <li><span>Доставка по Москве в пределах МКАД</span> рассчитывается исходя из суммы заказа:</li>
                        <ul>
                            <li>Заказ на сумму до 1000 руб. - доставка 100 руб.</li>
                            <li>Заказ на сумму от 1000 руб. - доставка бесплатно</li>
                        </ul>
                    </p>
                    <p>
                        <li><span>Доставка по Подмосковью</span> рассчитывается исходя из суммы заказа:</li>
                        <ul>
                            <li>Заказ на сумму до 1000 руб. - доставка 30 руб. за километр от МКАД, но не менее 300 руб.</li>
                            <li>Заказ на сумму от 1000 до 3000 руб. - доставка 20 руб. за километр от МКАД, но не менее 200 руб.</li>
                            <li>Заказ на сумму от 3000 до 6000 руб. - доставка 10 руб. за километр от МКАД, но не менее 100 руб.</li>
                            <li>Заказ на сумму от 6000 руб. - доставка бесплатно</li>
                        </ul>
                    </p>
                    <p>Доставка заказов по Подмосковью осуществляется в пределах 50 км от МКАД.</p>
                    <p>
                        <li><span>Доставка по России</span> рассчитывается исходя из суммы заказа:</li>
                        <ul>
                            <li>Заказ на сумму до 1000 руб. - 450 руб.</li>
                            <li>Заказ на сумму от 1000 до 6000 руб. - доставка 350 руб.</li>
                            <li>Заказ на сумму от 6000 руб. - доставка бесплатно</li>
                        </ul>
                    </p>
                    <p>Доставка по России осуществляется почтой РФ или транспортными компаниями.</p>
                </ul>
            </p>
            <p class="shipping_first_column_text">
                <h4>Формы оплаты</h4>
            <ul class="shipping_first_column_text payments">
                <li>
                    <span>Наличный расчет</span>. Вы оплачиваете заказ наличными курьеру при его получении. Для экономии времени при оплате заказа наличными, просим заранее приготовить требуемую сумму без сдачи.
                </li>
                <li>
                    <span>Денежный перевод на карту Сбербанка РФ</span>. Частным лицам после поступления заказа высылается бланк-извещение на оплату и номер банковской карты продавца в Сбербанке РФ.
                    После зачисления денег на карту нашего магазина мы доставим товар по указанному адресу.
                    Чтобы ускорить получение заказа, пожалуйста, сразу после перевода денег сообщите нам дату перевода и номер Вашего заказа.
                    В случае непоступления денежных средств в течение 7 дней Ваш заказ будет аннулирован.
                </li>
                <li>
                    <span>Банковский перевод</span>. Частным лицам после поступления заказа высылается бланк-извещение на оплату в Сбербанке РФ или любом другом банке.
                    После зачисления денежных средств на наш расчетный счет, мы доставим товар по указанному адресу.
                    Чтобы ускорить получение заказа, пожалуйста, сразу после перевода денег сообщите нам дату перевода и номер Вашего заказа.
                    В случае непоступления денежных средств в течение 7 дней Ваш заказ будет аннулирован.
                </li>
                <li>
                    <span>Безналичный расчет</span>. Юридическим лицам после поступления заказа высылается счет. После зачисления денежных средств на наш расчетный
                    счет, мы доставим товар по указанному адресу.
                    Чтобы ускорить получение заказа, пожалуйста, сразу после перевода денег сообщите нам дату перевода и номер счета. В случае
                    непоступления денежных средств в течение 7 дней Ваш заказ будет аннулирован.
                </li>
            </ul>
            </p>
        </div>
    </div>
    @include('partials.be_aware_of_sales')
    @include('partials.short_about')
@stop